### ISSUE TITLE
Instalação do módulo

### ISSUE THREAD

**Issue by tecbeto** [Diamix/magento2_correios#1]
Bom dia, eu fiz upload mesclando a pasta app do arquivo git com a pasta app em meu servidor. Após a mesclagem não surgiu nenhuma nova opção de configuração de métodos de envio de pacotes. O que posso fazer para resolver o problema? Obrigado.
![captura de tela de 2017-05-24 04-42-30](https://cloud.githubusercontent.com/assets/6409191/26392025/731ec2a6-403b-11e7-9dfb-6d546b3452ce.png)

**Comment by andregugliotti** [comment]
Olá!
No Magento 2, os módulos são sempre habilitados e desabilitados via linha de comando. Basta acessar o servidor onde sua loja está instalado via SSH, navegar até a pasta raiz da loja virtual e digitar:

**php bin/magento module:enable Diamix_Correios**

Depois, é preciso também fazer o update das configurações ou você encontrará um erro:

**php bin/magento setup:upgrade**

Para desabilitar o módulo, o comando é:

**php bin/magento module:disable Diamix_Correios**

Por último, é bom saber que existem as pastas cache e generation, dentro de /var. É sempre útil excluí-las, em ambiente de testes, para forçar sua reconstrução, quando mudanças são feitas.

**Comment by tecbeto** [comment]
Boa tarde, realizei todos os procedimentos que você orientou e o módulo apareceu corretamente no admin do Magento.
